SOURCE_TO_MODEL_FIELDS = [
    "company",
    "ticker",
    "fiscal_period",
    "model_section",
    "model_line",
    "mapping_treatment",
    "workbook_sheet",
    "workbook_cell",
    "source_metric",
    "source_value",
    "current_model_value",
    "proposed_model_value",
    "prior_value",
    "new_value",
    "delta",
    "delta_pct",
    "update_action",
    "overwrite_formula_allowed",
    "source_id",
    "source_name",
    "source_location",
    "evidence_label",
    "as_of_date",
    "freshness_status",
    "confidence",
    "review_status",
    "applied_to_workbook",
    "blocked_reason",
    "issue_flags",
]

CHANGE_LOG_FIELDS = [
    "change_id",
    "company",
    "ticker",
    "fiscal_period",
    "model_section",
    "model_line",
    "workbook_sheet",
    "workbook_cell",
    "current_model_value",
    "proposed_model_value",
    "delta",
    "delta_pct",
    "update_action",
    "change_reason",
    "source_id",
    "confidence",
    "status",
    "applied_to_workbook",
    "blocked_reason",
    "requires_model_audit_tieout",
]

TIEOUT_FIELDS = [
    "check_id",
    "check_area",
    "related_model_line",
    "workbook_sheet",
    "workbook_cell",
    "check_description",
    "owner",
    "status",
    "handoff_skill",
]

TRUTHY = {"1", "true", "yes", "y", "direct", "write", "edit"}
